### ISSUE TITLE
Serials...

### ISSUE THREAD

**Issue by bushy555** [Dronki/VZ200#1]
Hi,
Found your VZ repositry. Cool.
Attempted to do a pull request for this, but I am using an old browser in XP that doesn't support GitHubs 'Pull Request' menu item. It simply bombs out. Only other method to contact you was by creating an issue.

Further serial numbers for your VZ serial collection at :  https://github.com/Dronki/VZ200/blob/main/Serials.md
I too used to collect these years ago.

--

Dave Maunder
VZ200         ?          (dead)	  
VZ300 brown   V200502    (dead)
VZ300 brown   V201347    (dead)
VZ300 brown   ??         (dead)   - serial sticker missing
VZ300 brown   V203912    (working)
VZ300 cream   V228046    (dead)
VZ300 brown   ?	         (dead)
VZ300 brown   ?	         (dead)
VZ300 brown   ?	         (dead)

Jason Oakley
VZ300 cream   V230356     (working) 
VZ300 brown   ?           (working) 

Dean Thompson
VZ200         V017968     (working)
VZ300 cream   V229631	  (working)

Barry Hubble (Now Andrew Lairds)
VZ200         V076213     (working)
VZ300 brown   V202330     (working)
VZ300 cream   V234907     (working)

Guy Thomason
VZ300 brown   V170750     (working)
VZ300 brown   ??          (Dead)    - serial sticker missing

Ian Gledhill
Laser 210 		   

HaQue
VZ200         V030338      (P/S problem)
VZ300                      (dead???)   - serial sticker missing

Donovan Marshall
VZ200		V036385

Pete Hill
VZ200		036616
VZ200		036419
VZ200		038079
VZ200		077451
VZ200		036874

Random pics
VZ300		231251
VZ300		232207
VZ300		189189 
VZ300		225552
VZ300		231184
VZ300		235541

**Comment by Dronki** [comment]
Hi!
Sorry for the delayed response, I just saw this.
Awesome contribution! I will add them to the serial-list today or tomorrow :)
