### ISSUE TITLE
Another serial

### ISSUE THREAD

**Issue by bushy555** [Dronki/VZ200#4]
serial: 135987   Laser310. First Generation keyboard   (ie, no underneath markings on keys which I call a generation 2).
Video output : SEACAM.  ( 'seacam' sticker on the base near serial number)
Found in a group of pics via random google search.

**Comment by bushy555** [comment]
Serial:   024662.   4k VZ200 keyboard.  Video output : NTSC.
Found via random searching on Flickr.com

**Comment by bushy555** [comment]
v202348    Gen 2 vz300  (commands under keyboard, brown case).  Ebay. 25/oct/2022.

**Comment by Dronki** [comment]
Added, finally 👍
