### ISSUE TITLE
4x more...

### ISSUE THREAD

**Issue by bushy555** [Dronki/VZ200#5]
069599   Standard DSE VZ200, found on Aus ebay.
072894   Standard DSE VZ200, found on Aus ebay.
086797   Vtech 8k ram Laser200, found on Aus ebay. With what looks like a very good condition German VTECH packaging box.
202435   Standard DSE generation 1 VZ300, found on Aus ebay.

**Comment by bushy555** [comment]
074869.  VZ200. found on ebay sale. 9/Dec.

**Comment by Dronki** [comment]
Added
